language: ruby
rvm:
  - 1.9.3
before_install:
  - gem update --system
before_script:
  - "mysql -e 'create database thinking_sphinx;' > /dev/null"
  - "psql -c 'create database thinking_sphinx;' -U postgres >/dev/null"
env:
  - DATABASE=mysql2 SPHINX_BIN=/usr/local/sphinx-2.0.9/bin/ SPHINX_VERSION=2.0.9
gemfile:
  - gemfiles/rails_3_2.gemfile
